/* The following code was generated by JFlex 1.6.1 */

package scanner;

import java_cup.runtime.*;
import symbols.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>G:/git/Compilador-PCL/SCANNER/Scanner_PCL/src/scanner/pcl_rules.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\21\1\2\1\62\1\62\1\3\22\0\1\21\1\0\1\16"+
    "\1\17\4\0\1\4\1\6\1\5\1\53\1\51\1\12\1\13\1\1"+
    "\12\15\1\61\1\52\1\56\1\55\1\54\2\0\1\23\1\30\1\36"+
    "\1\25\1\14\1\43\1\31\1\40\1\32\1\20\1\47\1\34\1\45"+
    "\1\24\1\33\1\46\1\20\1\26\1\37\1\35\1\44\1\41\1\42"+
    "\1\50\1\27\1\20\1\57\1\0\1\60\1\0\1\20\1\0\32\20"+
    "\1\7\1\22\1\10\7\0\1\62\u05da\0\12\11\206\0\12\11\306\0"+
    "\12\11\u019c\0\12\11\166\0\12\11\166\0\12\11\166\0\12\11\166\0"+
    "\12\11\166\0\12\11\166\0\12\11\166\0\12\11\166\0\12\11\166\0"+
    "\12\11\140\0\12\11\166\0\12\11\106\0\12\11\u0116\0\12\11\106\0"+
    "\12\11\u0746\0\12\11\46\0\12\11\u012c\0\12\11\200\0\12\11\246\0"+
    "\12\11\6\0\12\11\266\0\12\11\126\0\12\11\206\0\12\11\6\0"+
    "\12\11\u03ce\0\1\62\1\62\u85f6\0\12\11\u02a6\0\12\11\46\0\12\11"+
    "\306\0\12\11\26\0\12\11\126\0\12\11\u0196\0\12\11\u5316\0\12\11"+
    "\u0586\0\12\11\u0bbc\0\12\11\200\0\12\11\74\0\12\11\220\0\12\11"+
    "\u0116\0\12\11\u01d6\0\12\11\u0176\0\12\11\146\0\12\11\u0216\0\12\11"+
    "\u5176\0\12\11\346\0\12\11\u6c74\0\62\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u280f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\11\4\1\1\3\23\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\0\1\25\1\0\1\23\1\7\2\0\1\26"+
    "\1\27\3\30\1\0\1\31\1\32\4\30\1\33\5\30"+
    "\2\33\23\30\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\2\23\2\0\1\44\1\0\1\30\1\33"+
    "\25\30\1\33\4\30\1\45\1\46\1\23\1\0\1\47"+
    "\1\30\1\33\23\30\1\33\15\30\1\33\10\30\1\33"+
    "\4\30\1\33\2\30\1\33\167\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[311];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\63\0\231\0\314\0\63\0\377"+
    "\0\u0132\0\u0165\0\63\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0231"+
    "\0\u0264\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9"+
    "\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561"+
    "\0\u0594\0\u05c7\0\u05fa\0\63\0\63\0\u062d\0\u0660\0\63"+
    "\0\u0693\0\63\0\63\0\u06c6\0\u06f9\0\63\0\u072c\0\63"+
    "\0\377\0\377\0\u075f\0\u0792\0\u07c5\0\63\0\63\0\u07f8"+
    "\0\u082b\0\u085e\0\u01cb\0\63\0\u01fe\0\u0891\0\u08c4\0\u08f7"+
    "\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f"+
    "\0\u07f8\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4"+
    "\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c"+
    "\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\63\0\63\0\u0e8b\0\63"+
    "\0\63\0\63\0\u0ebe\0\63\0\63\0\u0ef1\0\u0f24\0\u0f57"+
    "\0\u0f8a\0\u0fbd\0\u0ff0\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc"+
    "\0\u10ef\0\u1122\0\u1155\0\u1188\0\u11bb\0\u11ee\0\u1221\0\u1254"+
    "\0\u1287\0\u12ba\0\u12ed\0\u1320\0\u1353\0\u1386\0\u13b9\0\u13ec"+
    "\0\u141f\0\u1452\0\u1485\0\u14b8\0\u14eb\0\u151e\0\63\0\63"+
    "\0\u072c\0\u1551\0\u1551\0\u1584\0\u1584\0\u15b7\0\u15ea\0\u161d"+
    "\0\u1650\0\u1683\0\u16b6\0\u16e9\0\u171c\0\u174f\0\u1782\0\u17b5"+
    "\0\u17e8\0\u181b\0\u184e\0\u1881\0\u18b4\0\u18e7\0\u191a\0\u194d"+
    "\0\u194d\0\u1980\0\u19b3\0\u19e6\0\u1a19\0\u1a4c\0\u1a7f\0\u1ab2"+
    "\0\u1ae5\0\u1b18\0\u1b4b\0\u1b7e\0\u1bb1\0\u1be4\0\u1be4\0\u1c17"+
    "\0\u1c4a\0\u1c7d\0\u1cb0\0\u1ce3\0\u1d16\0\u1d49\0\u1d7c\0\u1d7c"+
    "\0\u1daf\0\u1de2\0\u1e15\0\u1e48\0\u1e48\0\u1e7b\0\u1eae\0\u1eae"+
    "\0\u1ee1\0\u1f14\0\u1f47\0\u1f7a\0\u1fad\0\u1fe0\0\u2013\0\u2046"+
    "\0\u2079\0\u20ac\0\u20df\0\u2112\0\u2145\0\u2178\0\u21ab\0\u21de"+
    "\0\u2211\0\u2244\0\u2277\0\u22aa\0\u22dd\0\u2310\0\u2343\0\u2376"+
    "\0\u23a9\0\u23dc\0\u240f\0\u2442\0\u2475\0\u24a8\0\u24db\0\u250e"+
    "\0\u2541\0\u2574\0\u25a7\0\u25da\0\u260d\0\u2640\0\u2673\0\u26a6"+
    "\0\u26d9\0\u270c\0\u273f\0\u2772\0\u27a5\0\u27d8\0\u280b\0\u283e"+
    "\0\u2871\0\u28a4\0\u28d7\0\u290a\0\u293d\0\u2970\0\u29a3\0\u29d6"+
    "\0\u2a09\0\u2a3c\0\u2a6f\0\u2aa2\0\u2ad5\0\u2b08\0\u2b3b\0\u2b6e"+
    "\0\u2ba1\0\u2bd4\0\u2c07\0\u2c3a\0\u2c6d\0\u2ca0\0\u2cd3\0\u2d06"+
    "\0\u2d39\0\u2d6c\0\u2d9f\0\u2dd2\0\u2e05\0\u2e38\0\u2e6b\0\u2e9e"+
    "\0\u2ed1\0\u2f04\0\u2f37\0\u2f6a\0\u2f9d\0\u2fd0\0\u3003\0\u3036"+
    "\0\u3069\0\u309c\0\u30cf\0\u3102\0\u3135\0\u3168\0\u319b\0\u31ce"+
    "\0\u3201\0\u3234\0\u3267\0\u329a\0\u32cd\0\u3300\0\u3333\0\u3366"+
    "\0\u3399\0\u33cc\0\u33ff\0\u3432\0\u3465\0\u3498\0\u34cb\0\u34fe"+
    "\0\u3531\0\u3564\0\u3597\0\u35ca\0\u35fd\0\u3630\0\63";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[311];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\13\1\14\1\11\1\15\1\16\1\17"+
    "\1\4\1\20\1\21\1\22\1\23\1\24\1\17\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\17"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\17\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\65\0\1\55\53\0\1\56\12\0\1\57\132\0"+
    "\1\60\5\0\10\61\1\62\52\61\11\0\1\63\1\0"+
    "\1\64\1\0\1\63\56\0\1\65\1\66\2\0\1\65"+
    "\37\0\1\67\21\0\2\70\2\0\1\70\1\0\2\70"+
    "\1\71\7\70\1\72\14\70\12\0\16\73\1\74\44\73"+
    "\11\0\1\75\3\0\1\75\61\0\2\70\2\0\1\70"+
    "\1\0\27\70\26\0\2\70\2\0\1\70\1\0\2\70"+
    "\1\71\1\70\1\76\22\70\26\0\2\70\2\0\1\70"+
    "\1\0\10\70\1\77\1\100\15\70\26\0\2\70\2\0"+
    "\1\70\1\0\10\70\1\101\1\102\15\70\26\0\1\103"+
    "\1\70\2\0\1\70\1\0\27\70\26\0\1\104\1\70"+
    "\2\0\1\70\1\0\5\70\1\105\3\70\1\106\15\70"+
    "\26\0\2\70\2\0\1\70\1\0\11\70\1\107\15\70"+
    "\26\0\2\70\2\0\1\70\1\0\2\70\1\110\16\70"+
    "\1\111\5\70\26\0\2\70\2\0\1\70\1\0\4\70"+
    "\1\111\14\70\1\111\5\70\26\0\2\70\2\0\1\70"+
    "\1\0\1\70\1\112\7\70\1\113\15\70\26\0\2\70"+
    "\2\0\1\70\1\0\4\70\1\114\1\115\3\70\1\111"+
    "\4\70\1\116\10\70\26\0\2\70\2\0\1\70\1\0"+
    "\1\70\1\72\7\70\1\117\4\70\1\120\10\70\26\0"+
    "\1\100\1\70\2\0\1\70\1\0\13\70\1\121\2\70"+
    "\1\122\10\70\26\0\2\70\2\0\1\70\1\0\1\70"+
    "\1\123\25\70\26\0\2\70\2\0\1\70\1\0\4\70"+
    "\1\124\3\70\1\125\5\70\1\126\10\70\26\0\2\70"+
    "\2\0\1\70\1\0\1\70\1\127\7\70\1\130\10\70"+
    "\1\131\4\70\26\0\2\70\2\0\1\70\1\0\2\70"+
    "\1\132\24\70\26\0\2\70\2\0\1\70\1\0\11\70"+
    "\1\71\15\70\26\0\2\70\2\0\1\70\1\0\1\70"+
    "\1\133\2\70\1\134\22\70\26\0\2\70\2\0\1\70"+
    "\1\0\11\70\1\123\15\70\65\0\1\135\1\0\1\136"+
    "\61\0\1\137\1\140\61\0\1\141\1\142\1\143\61\0"+
    "\1\144\5\0\2\55\1\145\1\146\57\55\5\57\1\147"+
    "\55\57\11\0\1\63\1\0\1\64\1\150\1\63\56\0"+
    "\1\151\3\0\1\151\56\0\1\152\1\0\1\64\1\0"+
    "\1\152\61\0\2\153\2\0\1\153\1\0\27\153\26\0"+
    "\2\153\2\0\1\153\1\0\3\153\1\154\23\153\26\0"+
    "\2\153\2\0\1\153\1\0\15\153\1\155\11\153\26\0"+
    "\2\153\2\0\1\153\1\0\4\153\1\156\22\153\26\0"+
    "\2\153\2\0\1\153\1\0\12\153\1\154\14\153\26\0"+
    "\2\153\2\0\1\153\1\0\13\153\1\154\13\153\26\0"+
    "\2\153\2\0\1\153\1\0\17\153\1\154\7\153\26\0"+
    "\2\153\2\0\1\153\1\0\20\153\1\157\6\153\26\0"+
    "\2\153\2\0\1\153\1\0\1\153\1\160\12\153\1\161"+
    "\7\153\1\162\2\153\26\0\2\153\2\0\1\153\1\0"+
    "\7\153\1\163\17\153\26\0\2\153\2\0\1\153\1\0"+
    "\13\153\1\155\13\153\26\0\2\153\2\0\1\153\1\0"+
    "\11\153\1\164\15\153\26\0\2\153\2\0\1\153\1\0"+
    "\13\153\1\165\13\153\26\0\2\153\2\0\1\153\1\0"+
    "\12\153\1\166\1\154\13\153\26\0\2\153\2\0\1\153"+
    "\1\0\6\153\1\167\20\153\26\0\2\153\2\0\1\153"+
    "\1\0\2\153\1\170\24\153\26\0\2\153\2\0\1\153"+
    "\1\0\22\153\1\155\4\153\26\0\2\153\2\0\1\153"+
    "\1\0\24\153\1\155\2\153\26\0\1\171\1\153\2\0"+
    "\1\153\1\0\27\153\26\0\2\153\2\0\1\153\1\0"+
    "\2\153\1\172\24\153\26\0\2\153\2\0\1\153\1\0"+
    "\1\153\1\173\25\153\26\0\2\153\2\0\1\153\1\0"+
    "\4\153\1\174\22\153\26\0\2\153\2\0\1\153\1\0"+
    "\11\153\1\175\15\153\26\0\2\153\2\0\1\153\1\0"+
    "\4\153\1\154\22\153\26\0\2\153\2\0\1\153\1\0"+
    "\10\153\1\176\16\153\26\0\2\153\2\0\1\153\1\0"+
    "\13\153\1\177\13\153\26\0\2\153\2\0\1\153\1\0"+
    "\10\153\1\200\16\153\26\0\2\153\2\0\1\153\1\0"+
    "\12\153\1\201\14\153\26\0\2\153\2\0\1\153\1\0"+
    "\4\153\1\202\22\153\26\0\2\153\2\0\1\153\1\0"+
    "\2\153\1\203\24\153\26\0\2\153\2\0\1\153\1\0"+
    "\13\153\1\204\13\153\26\0\2\153\2\0\1\153\1\0"+
    "\14\153\1\205\12\153\26\0\2\153\2\0\1\153\1\0"+
    "\11\153\1\206\15\153\67\0\1\207\62\0\1\210\7\0"+
    "\1\145\60\0\5\57\1\147\1\211\54\57\12\0\1\212"+
    "\2\0\1\213\56\0\1\151\2\0\1\150\1\151\56\0"+
    "\1\152\1\0\1\64\1\150\1\152\61\0\2\214\2\0"+
    "\1\214\1\0\27\214\26\0\1\215\1\214\2\0\1\214"+
    "\1\0\27\214\26\0\2\214\2\0\1\214\1\0\1\214"+
    "\1\216\25\214\26\0\2\214\2\0\1\214\1\0\2\214"+
    "\1\217\24\214\26\0\2\214\2\0\1\214\1\0\3\214"+
    "\1\215\6\214\1\215\14\214\26\0\2\214\2\0\1\214"+
    "\1\0\11\214\1\220\15\214\26\0\1\221\1\214\2\0"+
    "\1\214\1\0\27\214\26\0\2\214\2\0\1\214\1\0"+
    "\10\214\1\222\16\214\26\0\2\214\2\0\1\214\1\0"+
    "\12\214\1\223\14\214\26\0\2\214\2\0\1\214\1\0"+
    "\11\214\1\215\15\214\26\0\2\214\2\0\1\214\1\0"+
    "\10\214\1\224\16\214\26\0\1\225\1\214\2\0\1\214"+
    "\1\0\27\214\26\0\2\214\2\0\1\214\1\0\7\214"+
    "\1\226\17\214\26\0\2\214\2\0\1\214\1\0\2\214"+
    "\1\215\24\214\26\0\2\214\2\0\1\214\1\0\15\214"+
    "\1\227\11\214\26\0\2\214\2\0\1\214\1\0\4\214"+
    "\1\215\22\214\26\0\2\214\2\0\1\214\1\0\10\214"+
    "\1\230\16\214\26\0\2\214\2\0\1\214\1\0\4\214"+
    "\1\231\22\214\26\0\2\214\2\0\1\214\1\0\13\214"+
    "\1\232\13\214\26\0\2\214\2\0\1\214\1\0\16\214"+
    "\1\215\10\214\26\0\2\214\2\0\1\214\1\0\12\214"+
    "\1\232\14\214\26\0\2\214\2\0\1\214\1\0\15\214"+
    "\1\232\11\214\26\0\2\214\2\0\1\214\1\0\20\214"+
    "\1\233\6\214\26\0\2\214\2\0\1\214\1\0\14\214"+
    "\1\234\12\214\26\0\2\214\2\0\1\214\1\0\10\214"+
    "\1\225\16\214\26\0\2\214\2\0\1\214\1\0\25\214"+
    "\1\235\1\214\26\0\2\214\2\0\1\214\1\0\7\214"+
    "\1\236\4\214\1\237\12\214\27\0\1\213\61\0\2\240"+
    "\2\0\1\240\1\0\27\240\26\0\2\240\2\0\1\240"+
    "\1\0\5\240\1\241\21\240\26\0\2\240\2\0\1\240"+
    "\1\0\13\240\1\242\13\240\26\0\2\240\2\0\1\240"+
    "\1\0\4\240\1\243\22\240\26\0\2\240\2\0\1\240"+
    "\1\0\1\240\1\244\25\240\26\0\2\240\2\0\1\240"+
    "\1\0\2\240\1\241\24\240\26\0\1\245\1\240\2\0"+
    "\1\240\1\0\27\240\26\0\2\240\2\0\1\240\1\0"+
    "\2\240\1\246\24\240\26\0\2\240\2\0\1\240\1\0"+
    "\12\240\1\241\14\240\26\0\2\240\2\0\1\240\1\0"+
    "\10\240\1\247\16\240\26\0\2\240\2\0\1\240\1\0"+
    "\13\240\1\241\13\240\26\0\2\240\2\0\1\240\1\0"+
    "\2\240\1\250\24\240\26\0\2\240\2\0\1\240\1\0"+
    "\13\240\1\251\13\240\26\0\1\241\1\240\2\0\1\240"+
    "\1\0\27\240\26\0\2\240\2\0\1\240\1\0\1\240"+
    "\1\252\25\240\26\0\2\240\2\0\1\240\1\0\13\240"+
    "\1\253\13\240\26\0\1\243\1\240\2\0\1\240\1\0"+
    "\27\240\26\0\2\240\2\0\1\240\1\0\4\240\1\254"+
    "\22\240\26\0\1\255\1\240\2\0\1\240\1\0\27\240"+
    "\26\0\2\256\2\0\1\256\1\0\27\256\26\0\2\256"+
    "\2\0\1\256\1\0\11\256\1\257\15\256\26\0\2\256"+
    "\2\0\1\256\1\0\3\256\1\257\23\256\26\0\2\256"+
    "\2\0\1\256\1\0\13\256\1\257\13\256\26\0\2\256"+
    "\2\0\1\256\1\0\1\256\1\260\25\256\26\0\1\257"+
    "\1\256\2\0\1\256\1\0\27\256\26\0\2\256\2\0"+
    "\1\256\1\0\2\256\1\261\24\256\26\0\2\256\2\0"+
    "\1\256\1\0\7\256\1\257\17\256\26\0\2\256\2\0"+
    "\1\256\1\0\10\256\1\262\16\256\26\0\2\256\2\0"+
    "\1\256\1\0\4\256\1\263\22\256\26\0\2\256\2\0"+
    "\1\256\1\0\10\256\1\264\16\256\26\0\2\256\2\0"+
    "\1\256\1\0\1\256\1\265\25\256\26\0\2\256\2\0"+
    "\1\256\1\0\3\256\1\266\23\256\26\0\2\267\2\0"+
    "\1\267\1\0\27\267\26\0\2\267\2\0\1\267\1\0"+
    "\2\267\1\270\24\267\26\0\2\267\2\0\1\267\1\0"+
    "\13\267\1\270\13\267\26\0\2\267\2\0\1\267\1\0"+
    "\2\267\1\271\24\267\26\0\2\267\2\0\1\267\1\0"+
    "\3\267\1\270\23\267\26\0\2\267\2\0\1\267\1\0"+
    "\11\267\1\272\15\267\26\0\2\267\2\0\1\267\1\0"+
    "\23\267\1\270\3\267\26\0\2\267\2\0\1\267\1\0"+
    "\22\267\1\273\4\267\26\0\2\274\2\0\1\274\1\0"+
    "\27\274\26\0\2\274\2\0\1\274\1\0\13\274\1\275"+
    "\13\274\26\0\2\274\2\0\1\274\1\0\2\274\1\275"+
    "\24\274\26\0\2\274\2\0\1\274\1\0\4\274\1\276"+
    "\22\274\26\0\2\277\2\0\1\277\1\0\27\277\26\0"+
    "\1\300\1\277\2\0\1\277\1\0\27\277\26\0\2\301"+
    "\2\0\1\301\1\0\27\301\26\0\2\302\2\0\1\302"+
    "\1\0\27\302\26\0\2\303\2\0\1\303\1\0\27\303"+
    "\26\0\2\304\2\0\1\304\1\0\27\304\26\0\2\305"+
    "\2\0\1\305\1\0\27\305\26\0\2\306\2\0\1\306"+
    "\1\0\27\306\26\0\2\307\2\0\1\307\1\0\27\307"+
    "\26\0\2\310\2\0\1\310\1\0\27\310\26\0\2\311"+
    "\2\0\1\311\1\0\27\311\26\0\2\312\2\0\1\312"+
    "\1\0\27\312\26\0\2\313\2\0\1\313\1\0\27\313"+
    "\26\0\2\314\2\0\1\314\1\0\27\314\26\0\2\315"+
    "\2\0\1\315\1\0\27\315\26\0\2\316\2\0\1\316"+
    "\1\0\27\316\26\0\2\317\2\0\1\317\1\0\27\317"+
    "\26\0\2\320\2\0\1\320\1\0\27\320\26\0\2\321"+
    "\2\0\1\321\1\0\27\321\26\0\2\322\2\0\1\322"+
    "\1\0\27\322\26\0\2\323\2\0\1\323\1\0\27\323"+
    "\26\0\2\324\2\0\1\324\1\0\27\324\26\0\2\325"+
    "\2\0\1\325\1\0\27\325\26\0\2\326\2\0\1\326"+
    "\1\0\27\326\26\0\2\327\2\0\1\327\1\0\27\327"+
    "\26\0\2\330\2\0\1\330\1\0\27\330\26\0\2\331"+
    "\2\0\1\331\1\0\27\331\26\0\2\332\2\0\1\332"+
    "\1\0\27\332\26\0\2\333\2\0\1\333\1\0\27\333"+
    "\26\0\2\334\2\0\1\334\1\0\27\334\26\0\2\335"+
    "\2\0\1\335\1\0\27\335\26\0\2\336\2\0\1\336"+
    "\1\0\27\336\26\0\2\337\2\0\1\337\1\0\27\337"+
    "\26\0\2\340\2\0\1\340\1\0\27\340\26\0\2\341"+
    "\2\0\1\341\1\0\27\341\26\0\2\342\2\0\1\342"+
    "\1\0\27\342\26\0\2\343\2\0\1\343\1\0\27\343"+
    "\26\0\2\344\2\0\1\344\1\0\27\344\26\0\2\345"+
    "\2\0\1\345\1\0\27\345\26\0\2\346\2\0\1\346"+
    "\1\0\27\346\26\0\2\347\2\0\1\347\1\0\27\347"+
    "\26\0\2\350\2\0\1\350\1\0\27\350\26\0\2\351"+
    "\2\0\1\351\1\0\27\351\26\0\2\352\2\0\1\352"+
    "\1\0\27\352\26\0\2\353\2\0\1\353\1\0\27\353"+
    "\26\0\2\354\2\0\1\354\1\0\27\354\26\0\2\355"+
    "\2\0\1\355\1\0\27\355\26\0\2\356\2\0\1\356"+
    "\1\0\27\356\26\0\2\357\2\0\1\357\1\0\27\357"+
    "\26\0\2\360\2\0\1\360\1\0\27\360\26\0\2\361"+
    "\2\0\1\361\1\0\27\361\26\0\2\362\2\0\1\362"+
    "\1\0\27\362\26\0\2\363\2\0\1\363\1\0\27\363"+
    "\26\0\2\364\2\0\1\364\1\0\27\364\26\0\2\365"+
    "\2\0\1\365\1\0\27\365\26\0\2\366\2\0\1\366"+
    "\1\0\27\366\26\0\2\367\2\0\1\367\1\0\27\367"+
    "\26\0\2\370\2\0\1\370\1\0\27\370\26\0\2\371"+
    "\2\0\1\371\1\0\27\371\26\0\2\372\2\0\1\372"+
    "\1\0\27\372\26\0\2\373\2\0\1\373\1\0\27\373"+
    "\26\0\2\374\2\0\1\374\1\0\27\374\26\0\2\375"+
    "\2\0\1\375\1\0\27\375\26\0\2\376\2\0\1\376"+
    "\1\0\27\376\26\0\2\377\2\0\1\377\1\0\27\377"+
    "\26\0\2\u0100\2\0\1\u0100\1\0\27\u0100\26\0\2\u0101"+
    "\2\0\1\u0101\1\0\27\u0101\26\0\2\u0102\2\0\1\u0102"+
    "\1\0\27\u0102\26\0\2\u0103\2\0\1\u0103\1\0\27\u0103"+
    "\26\0\2\u0104\2\0\1\u0104\1\0\27\u0104\26\0\2\u0105"+
    "\2\0\1\u0105\1\0\27\u0105\26\0\2\u0106\2\0\1\u0106"+
    "\1\0\27\u0106\26\0\2\u0107\2\0\1\u0107\1\0\27\u0107"+
    "\26\0\2\u0108\2\0\1\u0108\1\0\27\u0108\26\0\2\u0109"+
    "\2\0\1\u0109\1\0\27\u0109\26\0\2\u010a\2\0\1\u010a"+
    "\1\0\27\u010a\26\0\2\u010b\2\0\1\u010b\1\0\27\u010b"+
    "\26\0\2\u010c\2\0\1\u010c\1\0\27\u010c\26\0\2\u010d"+
    "\2\0\1\u010d\1\0\27\u010d\26\0\2\u010e\2\0\1\u010e"+
    "\1\0\27\u010e\26\0\2\u010f\2\0\1\u010f\1\0\27\u010f"+
    "\26\0\2\u0110\2\0\1\u0110\1\0\27\u0110\26\0\2\u0111"+
    "\2\0\1\u0111\1\0\27\u0111\26\0\2\u0112\2\0\1\u0112"+
    "\1\0\27\u0112\26\0\2\u0113\2\0\1\u0113\1\0\27\u0113"+
    "\26\0\2\u0114\2\0\1\u0114\1\0\27\u0114\26\0\2\u0115"+
    "\2\0\1\u0115\1\0\27\u0115\26\0\2\u0116\2\0\1\u0116"+
    "\1\0\27\u0116\26\0\2\u0117\2\0\1\u0117\1\0\27\u0117"+
    "\26\0\2\u0118\2\0\1\u0118\1\0\27\u0118\26\0\2\u0119"+
    "\2\0\1\u0119\1\0\27\u0119\26\0\2\u011a\2\0\1\u011a"+
    "\1\0\27\u011a\26\0\2\u011b\2\0\1\u011b\1\0\27\u011b"+
    "\26\0\2\u011c\2\0\1\u011c\1\0\27\u011c\26\0\2\u011d"+
    "\2\0\1\u011d\1\0\27\u011d\26\0\2\u011e\2\0\1\u011e"+
    "\1\0\27\u011e\26\0\2\u011f\2\0\1\u011f\1\0\27\u011f"+
    "\26\0\2\u0120\2\0\1\u0120\1\0\27\u0120\26\0\2\u0121"+
    "\2\0\1\u0121\1\0\27\u0121\26\0\2\u0122\2\0\1\u0122"+
    "\1\0\27\u0122\26\0\2\u0123\2\0\1\u0123\1\0\27\u0123"+
    "\26\0\2\u0124\2\0\1\u0124\1\0\27\u0124\26\0\2\u0125"+
    "\2\0\1\u0125\1\0\27\u0125\26\0\2\u0126\2\0\1\u0126"+
    "\1\0\27\u0126\26\0\2\u0127\2\0\1\u0127\1\0\27\u0127"+
    "\26\0\2\u0128\2\0\1\u0128\1\0\27\u0128\26\0\2\u0129"+
    "\2\0\1\u0129\1\0\27\u0129\26\0\2\u012a\2\0\1\u012a"+
    "\1\0\27\u012a\26\0\2\u012b\2\0\1\u012b\1\0\27\u012b"+
    "\26\0\2\u012c\2\0\1\u012c\1\0\27\u012c\26\0\2\u012d"+
    "\2\0\1\u012d\1\0\27\u012d\26\0\2\u012e\2\0\1\u012e"+
    "\1\0\27\u012e\26\0\2\u012f\2\0\1\u012f\1\0\27\u012f"+
    "\26\0\2\u0130\2\0\1\u0130\1\0\27\u0130\26\0\2\u0131"+
    "\2\0\1\u0131\1\0\27\u0131\26\0\2\u0132\2\0\1\u0132"+
    "\1\0\27\u0132\26\0\2\u0133\2\0\1\u0133\1\0\27\u0133"+
    "\26\0\2\u0134\2\0\1\u0134\1\0\27\u0134\26\0\2\u0135"+
    "\2\0\1\u0135\1\0\27\u0135\26\0\2\u0136\2\0\1\u0136"+
    "\1\0\27\u0136\26\0\2\u0137\2\0\1\u0137\1\0\27\u0137"+
    "\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[13923];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\1\11\3\1\1\11"+
    "\30\1\2\11\2\1\1\11\1\1\2\11\2\1\1\11"+
    "\1\0\1\11\1\0\2\1\2\0\2\11\3\1\1\0"+
    "\1\11\40\1\2\11\1\1\3\11\1\1\2\11\1\1"+
    "\2\0\1\1\1\0\34\1\2\11\1\1\1\0\254\1"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[311];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
private Symbol token(int type, Object value)
{
    return new Symbol(type, yyline, yycolumn, value);
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 364) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return token(sym.ERROR_LEXICO, "Caracter inválido " + yytext());
            }
          case 40: break;
          case 2: 
            { return token(sym.OP_DIVISION, yytext());
            }
          case 41: break;
          case 3: 
            { /*Omitir el espacio blanco*/
            }
          case 42: break;
          case 4: 
            { return token(sym.PAR_APER, yytext());
            }
          case 43: break;
          case 5: 
            { return token(sym.OP_MULTIPLICACION, yytext());
            }
          case 44: break;
          case 6: 
            { return token(sym.PAR_CERR, yytext());
            }
          case 45: break;
          case 7: 
            { return token(sym.ENTERO, yytext());
            }
          case 46: break;
          case 8: 
            { return token(sym.OP_RESTA, yytext());
            }
          case 47: break;
          case 9: 
            { return token(sym.PUNTO, yytext());
            }
          case 48: break;
          case 10: 
            { return token(sym.COMA, yytext());
            }
          case 49: break;
          case 11: 
            { return token(sym.PUNTO_COMA, yytext());
            }
          case 50: break;
          case 12: 
            { return token(sym.OP_SUMA, yytext());
            }
          case 51: break;
          case 13: 
            { return token(sym.OP_MAYOR, yytext());
            }
          case 52: break;
          case 14: 
            { return token(sym.OP_IGUAL, yytext());
            }
          case 53: break;
          case 15: 
            { return token(sym.OP_MENOR, yytext());
            }
          case 54: break;
          case 16: 
            { return token(sym.BRA_APER, yytext());
            }
          case 55: break;
          case 17: 
            { return token(sym.BRA_CERR, yytext());
            }
          case 56: break;
          case 18: 
            { return token(sym.DOS_PUNTO, yytext());
            }
          case 57: break;
          case 19: 
            { return token(sym.COMMENT, yytext());
            }
          case 58: break;
          case 20: 
            { return token(sym.OP_DIV_ASIGN, yytext());
            }
          case 59: break;
          case 21: 
            { return token(sym.OP_MUL_ASIGN, yytext());
            }
          case 60: break;
          case 22: 
            { return token(sym.OP_DEC, yytext());
            }
          case 61: break;
          case 23: 
            { return token(sym.OP_RESTA_ASIGN, yytext());
            }
          case 62: break;
          case 24: 
            { return token(sym.ID, yytext().toUpperCase());
            }
          case 63: break;
          case 25: 
            { return token(sym.STRING_C, yytext());
            }
          case 64: break;
          case 26: 
            { return token(sym.CHARACTER, yytext());
            }
          case 65: break;
          case 27: 
            { return token(sym.PALABRA_RESERVADA, yytext());
            }
          case 66: break;
          case 28: 
            { return token(sym.OP_INC, yytext());
            }
          case 67: break;
          case 29: 
            { return token(sym.OP_SUMA_ASIGN, yytext());
            }
          case 68: break;
          case 30: 
            { return token(sym.OP_SHIFT_DER, yytext());
            }
          case 69: break;
          case 31: 
            { return token(sym.OP_MAYOR_IGUAL, yytext());
            }
          case 70: break;
          case 32: 
            { return token(sym.OP_DISTINTO, yytext());
            }
          case 71: break;
          case 33: 
            { return token(sym.OP_MENOR_IGUAL, yytext());
            }
          case 72: break;
          case 34: 
            { return token(sym.OP_SHIFT_IZQ, yytext());
            }
          case 73: break;
          case 35: 
            { return token(sym.ASIGN, yytext());
            }
          case 74: break;
          case 36: 
            { return token(sym.FLOTANTE, yytext());
            }
          case 75: break;
          case 37: 
            { return token(sym.OP_SHIFT_DER_ASIGN, yytext());
            }
          case 76: break;
          case 38: 
            { return token(sym.OP_SHIFT_IZQ_ASIGN, yytext());
            }
          case 77: break;
          case 39: 
            { return token(sym.NOTA_CIENTIFICA, yytext());
            }
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
