
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 08 21:52:05 CST 2016
//----------------------------------------------------

package logica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int char_ = 35;
  public static final int identificador = 2;
  public static final int finally_ = 27;
  public static final int binario_literal = 84;
  public static final int menos_igual = 46;
  public static final int float_ = 32;
  public static final int punto = 72;
  public static final int string_literal = 90;
  public static final int shift_derecha = 65;
  public static final int suma = 37;
  public static final int char_valor = 89;
  public static final int boolean_ = 33;
  public static final int for_ = 30;
  public static final int import_ = 10;
  public static final int ampersand = 61;
  public static final int menor_igual = 57;
  public static final int circunflejo = 63;
  public static final int resta = 38;
  public static final int flotante_literal = 86;
  public static final int continue_ = 15;
  public static final int parentesis_cierra = 70;
  public static final int list = 34;
  public static final int multiplicacion = 39;
  public static final int mayor_igual = 56;
  public static final int else_ = 26;
  public static final int with_ = 6;
  public static final int ERROR = 91;
  public static final int try_ = 21;
  public static final int division_igual = 48;
  public static final int division_doble = 41;
  public static final int range = 19;
  public static final int is = 17;
  public static final int menor_ = 55;
  public static final int string = 36;
  public static final int binario_long = 85;
  public static final int in = 20;
  public static final int or = 60;
  public static final int this_ = 13;
  public static final int not_igual = 52;
  public static final int while_ = 24;
  public static final int salto_linea = 93;
  public static final int from = 4;
  public static final int break_ = 14;
  public static final int decimal_literal = 78;
  public static final int true_ = 76;
  public static final int igual_igual = 58;
  public static final int and = 59;
  public static final int mayor = 54;
  public static final int octal_literal = 82;
  public static final int lambda = 12;
  public static final int multiplicacion_igual = 47;
  public static final int mas_igual = 45;
  public static final int pass = 8;
  public static final int hexa_long = 81;
  public static final int division = 40;
  public static final int EOF = 0;
  public static final int if_ = 23;
  public static final int as = 5;
  public static final int dos_puntos = 73;
  public static final int potencia_igual = 50;
  public static final int elif = 25;
  public static final int double_literal = 87;
  public static final int cuadrado_cierra = 75;
  public static final int return_ = 18;
  public static final int not_symbol = 68;
  public static final int assert_ = 7;
  public static final int yield = 9;
  public static final int potencia = 43;
  public static final int tilde = 64;
  public static final int error = 1;
  public static final int decimal_long = 79;
  public static final int except = 22;
  public static final int char_literal = 92;
  public static final int octal_long = 83;
  public static final int string_valor = 88;
  public static final int cuadrado_abre = 74;
  public static final int class_ = 29;
  public static final int division_doble_igual = 51;
  public static final int menor_mayor = 53;
  public static final int parentesis_abre = 69;
  public static final int del = 3;
  public static final int coma = 71;
  public static final int modulo = 42;
  public static final int shift_izquierda = 66;
  public static final int not = 67;
  public static final int igual = 44;
  public static final int pipe = 62;
  public static final int def = 28;
  public static final int false_ = 77;
  public static final int print_ = 95;
  public static final int punto_coma = 94;
  public static final int exec = 11;
  public static final int int_ = 31;
  public static final int input = 16;
  public static final int hexa_literal = 80;
  public static final int modulo_igual = 49;
}

