
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 04 19:35:01 CST 2016
//----------------------------------------------------

package logica.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 3;
  public static final int LONGINT = 4;
  public static final int PUNTO_COMA = 11;
  public static final int BOOLEAN = 8;
  public static final int EOF = 0;
  public static final int SHORTINT = 5;
  public static final int STRING = 7;
  public static final int VAR = 2;
  public static final int DOS_PUNTO = 12;
  public static final int ID = 10;
  public static final int REAL = 9;
  public static final int error = 1;
  public static final int CHAR = 6;
}

