
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 05 17:46:37 CST 2016
//----------------------------------------------------

package logica.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 16;
  public static final int PROGRAM = 2;
  public static final int INT = 4;
  public static final int LONGINT = 5;
  public static final int PUNTO_COMA = 12;
  public static final int BOOLEAN = 9;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int SHORTINT = 6;
  public static final int VAR = 3;
  public static final int DOS_PUNTO = 13;
  public static final int ID = 11;
  public static final int REAL = 10;
  public static final int error = 1;
  public static final int END = 15;
  public static final int BEGIN = 14;
  public static final int CHAR = 7;
}

