
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 13 14:43:37 CST 2016
//----------------------------------------------------

package logica.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _const = 10;
  public static final int _bra_cerr = 41;
  public static final int _parentesisCierra = 36;
  public static final int _array = 21;
  public static final int _shortint = 24;
  public static final int _true = 32;
  public static final int _write = 64;
  public static final int _op_multi = 51;
  public static final int _bra_aper = 40;
  public static final int _coma = 39;
  public static final int _do = 19;
  public static final int _igual = 34;
  public static final int _op_DIV = 54;
  public static final int _NOT = 62;
  public static final int _AND = 61;
  public static final int _op_division = 52;
  public static final int _real = 27;
  public static final int _procedure = 15;
  public static final int _begin = 5;
  public static final int _until = 13;
  public static final int _OR = 60;
  public static final int _end = 6;
  public static final int _else = 9;
  public static final int _op_div_igual = 47;
  public static final int _read = 65;
  public static final int _op_mult_igual = 48;
  public static final int _op_menos_igual = 46;
  public static final int _flotante = 31;
  public static final int _boolean = 26;
  public static final int _asignacion = 49;
  public static final int _program = 2;
  public static final int _then = 16;
  public static final int _var = 3;
  public static final int EOF = 0;
  public static final int _string = 4;
  public static final int _menor = 58;
  public static final int _function = 14;
  public static final int _distinto = 59;
  public static final int _op_resta = 50;
  public static final int error = 1;
  public static final int _parentesisAbre = 35;
  public static final int _mayor = 56;
  public static final int _op_suma = 44;
  public static final int _hilera = 29;
  public static final int _op_mas_igual = 45;
  public static final int _punto = 42;
  public static final int _if = 7;
  public static final int _id = 63;
  public static final int _mayor_igual = 55;
  public static final int _while = 20;
  public static final int _of = 12;
  public static final int _int = 22;
  public static final int _char = 25;
  public static final int _for = 18;
  public static final int _entero = 28;
  public static final int _caracter = 30;
  public static final int _case = 11;
  public static final int _repeat = 8;
  public static final int _menor_igual = 57;
  public static final int _false = 33;
  public static final int _rango_dos_puntos = 43;
  public static final int _dos_puntos = 37;
  public static final int _longint = 23;
  public static final int _op_mod = 53;
  public static final int _punto_coma = 38;
  public static final int _to = 17;
}

