package symbols;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 23 11:01:34 CST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 4;
  public static final int SUMA = 6;
  public static final int ENTERO = 7;
  public static final int THEN = 3;
  public static final int EOF = 0;
  public static final int IF = 2;
  public static final int ID = 5;
  public static final int error = 1;
  public static final int COMMENT = 8;
}

