package symbols;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 01 13:41:29 CST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_MAYOR = 8;
  public static final int DOS_PUNTO = 23;
  public static final int COMMENT = 39;
  public static final int STRING_C = 35;
  public static final int ENTERO = 32;
  public static final int OP_MULTIPLICACION = 15;
  public static final int OP_SHIFT_DER = 28;
  public static final int OP_INC = 5;
  public static final int CHARACTER = 36;
  public static final int SUMA = 38;
  public static final int NOTA_CIENTIFICA = 34;
  public static final int ID = 37;
  public static final int PUNTO_COMA = 4;
  public static final int OP_SUMA_ASIGN = 24;
  public static final int EOF = 0;
  public static final int OP_DIVISION = 16;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int OP_RESTA = 14;
  public static final int PALABRA_RESERVADA = 2;
  public static final int PAR_CERR = 18;
  public static final int OP_DISTINTO = 11;
  public static final int OP_MAYOR_IGUAL = 7;
  public static final int OP_MUL_ASIGN = 26;
  public static final int PUNTO = 22;
  public static final int OP_IGUAL = 12;
  public static final int OP_SHIFT_IZQ_ASIGN = 30;
  public static final int PAR_APER = 17;
  public static final int OP_DEC = 6;
  public static final int BRA_CERR = 20;
  public static final int OP_MENOR_IGUAL = 9;
  public static final int ASIGN = 21;
  public static final int OP_SHIFT_IZQ = 29;
  public static final int OP_SUMA = 13;
  public static final int BRA_APER = 19;
  public static final int OP_SHIFT_DER_ASIGN = 31;
  public static final int FLOTANTE = 33;
  public static final int OP_DIV_ASIGN = 27;
  public static final int OP_RESTA_ASIGN = 25;
  public static final int OP_MENOR = 10;
  
  public static final int ERROR_LEXICO = -100;
  
  public static String getValue(int pValue)
  {
      String res = "";
      
      switch(pValue)
      {
          case OP_MAYOR:
              return "Operador Mayor";
          case DOS_PUNTO:
              return "Dos puntos";
          case COMMENT:
              return "Comentario";
          case STRING_C:
              return "Literal Hilera";
          case ENTERO:
                return "Literal Número entero";
            case OP_MULTIPLICACION:
                return "Operador Multiplicación";
            case OP_SHIFT_DER:
                return "Operador corrimiento hacia la derecha";
            case OP_INC:
                return "Operador Incremento";
            case CHARACTER:
                return "Literal  Caracter";
            case SUMA:
                return "Operador adición";
            case NOTA_CIENTIFICA:
                return "Literal Notación científica";
            case ID:
                return "Identificador";
            case PUNTO_COMA:
                return "Punto y coma";
            case OP_SUMA_ASIGN:
                return "Operador Suma y asignación";
            case OP_DIVISION:
                return "Operador División";
            case COMA:
                return "Coma";
            case OP_RESTA:
                return "Operador Resta";
            case PALABRA_RESERVADA:
                return "Palabra reservada";
            case PAR_CERR:
                return "Paréntesis derecho";
            case OP_DISTINTO:
                return "Operador de desigualdad";
            case OP_MAYOR_IGUAL:
                return "Operador Mayor o igual";
            case OP_MUL_ASIGN :
                return "Operador Multiplicación y asignación";
            case PUNTO:
                return "Punto";
            case OP_IGUAL:
                return "Operador Igual";
            case OP_SHIFT_IZQ_ASIGN:
                return "Operador Corrimiento hacia la izquierda y asignación";
            case PAR_APER:
                return "Paréntesis izquierdo";
            case OP_DEC:
                return "Operador Decremento";
            case BRA_CERR:
                return "Bracket derecho";
            case OP_MENOR_IGUAL:
                return "Operador Menor o igual";
            case ASIGN:
                return "Asignación";
            case OP_SHIFT_IZQ:
                return "Operador Corrimiento hacia la izquierda";
            case OP_SUMA :
                return "Operador Suma";
            case BRA_APER:
                return "Bracket izquierdo";
            case OP_SHIFT_DER_ASIGN:
                return "Operador Corrimiento hacia la derecha y asignación";
            case FLOTANTE:
                return "Literal Número flotante";
            case OP_DIV_ASIGN:
                return "Operador División y asignación";
            case OP_RESTA_ASIGN:
                return "Operador Resta y asignación";
            case OP_MENOR: 
                return "Operador Menor";
            default:
                return res + "No hallado";
      }

  }
  
}


