package symbols;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 30 19:30:48 CST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 19;
  public static final int WITH = 49;
  public static final int CONST = 9;
  public static final int PACKED = 32;
  public static final int CHAR = 8;
  public static final int COMMENT = 59;
  public static final int STRING_C = 55;
  public static final int ENTERO = 52;
  public static final int XOR = 51;
  public static final int CASE = 7;
  public static final int REPEAT = 38;
  public static final int INT = 24;
  public static final int ARRAY = 3;
  public static final int FORWARD = 18;
  public static final int FOR = 17;
  public static final int WRITE = 50;
  public static final int CHARACTER = 56;
  public static final int NOT = 29;
  public static final int AND = 2;
  public static final int RECORD = 37;
  public static final int TYPE = 45;
  public static final int NIL = 28;
  public static final int IN = 22;
  public static final int OR = 31;
  public static final int DIV = 10;
  public static final int BEGIN = 4;
  public static final int UNTIL = 46;
  public static final int SUMA = 58;
  public static final int NOTA_CIENTIFICA = 54;
  public static final int IF = 21;
  public static final int ID = 57;
  public static final int OF = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int TRUE = 44;
  public static final int error = 1;
  public static final int PROGRAM = 34;
  public static final int MOD = 27;
  public static final int BYTE = 6;
  public static final int REAL = 36;
  public static final int SHORTINT = 40;
  public static final int ELSE = 13;
  public static final int READ = 35;
  public static final int TO = 43;
  public static final int FILE = 16;
  public static final int GOTO = 20;
  public static final int WHILE = 48;
  public static final int THEN = 42;
  public static final int END = 14;
  public static final int STRING = 41;
  public static final int DOWNTO = 12;
  public static final int INLINE = 23;
  public static final int FALSE = 15;
  public static final int LABEL = 25;
  public static final int FLOTANTE = 53;
  public static final int VAR = 47;
  public static final int LONGINT = 26;
  public static final int PROCEDURE = 33;
  public static final int DO = 11;
  public static final int SET = 39;
}

